[project]
name = "NLPClassifierExplainer"
version = "0.0.2"
authors = [
  { name="Bruno Fleisch", email="bruno.fleisch@bt.com" },
]
description = "A simple explainer for NLP classification task"
requires-python = ">=3.7"

